version: "3.9"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    container_name: self-deploy-gitlab
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
    networks:
      - self_deploy_net

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: self-deploy-gitlab-runner
    depends_on:
      - gitlab
    environment:
      - CI_SERVER_URL=http://gitlab:80
      - REGISTRATION_TOKEN=${GITLAB_RUNNER_TOKEN:-CHANGEME}
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine:latest
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - self_deploy_net

  sonar_db:
    image: postgres:15
    container_name: self-deploy-sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - self_deploy_net

  sonarqube:
    image: sonarqube:latest
    container_name: self-deploy-sonarqube
    depends_on:
      - sonar_db
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - self_deploy_net

  nexus:
    image: sonatype/nexus3:latest
    container_name: self-deploy-nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - self_deploy_net

networks:
  self_deploy_net:
    driver: bridge

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  gitlab_runner_config:
  sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
